#!/bin/bash
#This script depends on the: flac, ffmpeg and mpeg4ip-utils packages.

dirlist=()
for f in /media/Musikk/Musikk/FLAC/*/*; do # for each item in test/ ...
	if [ -d "$f" ]; then # if it's a subdir...
		dirlist=("${dirlist[@]}" "$f") # add it to the list
		echo $f
	fi
done

for direc in "${dirlist[@]}"; do
   echo "Found " $direc
   for a in "$direc/"*.flac
     do
         OUTF=`echo "$a" | sed s/"\.flac$"/"\.m4a"/g`

         ARTIST=`metaflac "$a" --show-tag=ARTIST | sed s/.*=//g`
         TITLE=`metaflac "$a" --show-tag=TITLE | sed s/.*=//g`
         ALBUM=`metaflac "$a" --show-tag=ALBUM | sed s/.*=//g`
         GENRE=`metaflac "$a" --show-tag=GENRE | sed s/.*=//g`
         TRACKNUMBER=`metaflac "$a" --show-tag=TRACKNUMBER | sed s/.*=//g`
         DATE=`metaflac "$a" --show-tag=DATE | sed s/.*=//g`

	 mkdir -p "/media/Musikk/ALAC/$ARTIST/[$DATE] $ALBUM"
	
         flac -c -d "$a" | ffmpeg -i - -acodec alac "$OUTF"
         mp4tags -s "$TITLE" -t "$TRACKNUMBER" -a "$ARTIST" -A "$ALBUM" -g "$GENRE" -y "$DATE" "$ARTIST - $ALBUM - $TRACKNUMBER - $TITLE".m4a
	 echo "File: " $OUTF
	 mv "$OUTF" "/media/Musikk/ALAC/$ARTIST/[$DATE] $ALBUM/"
      done
done
fi
