#!/bin/bash
#This script depends on the: flac, ffmpeg and mpeg4ip-utils packages.

dirlist=()
for f in /media/Musikk/Musikk/FLAC/*/*; do # for each item in test/ ...
	if [ -d "$f" ]; then # if it's a subdir...
		dirlist=("${dirlist[@]}" "$f") # add it to the list
		echo $f
	fi
done

#a=$(find /media/Musikk/Musikk/FLAC/ -type d -mindepth 2) | while read a ; do
#dirlist=$(ls -d /media/Musikk/Musikk/FLAC/*/*/)
#echo $dirlist
#for direc in $dirlist ; do
for direc in "${dirlist[@]}"; do
   echo "DIREC:" $direc
   for a in "$direc/"*.flac
#    for a in $(find /media/Musikk/Musikk/FLAC -name '*.flac')
     do
         OUTF=`echo "$a" | sed s/"\.flac$"/"\.m4a"/g`

         ARTIST=`metaflac "$a" --show-tag=ARTIST | sed s/.*=//g`
         TITLE=`metaflac "$a" --show-tag=TITLE | sed s/.*=//g`
         ALBUM=`metaflac "$a" --show-tag=ALBUM | sed s/.*=//g`
         GENRE=`metaflac "$a" --show-tag=GENRE | sed s/.*=//g`
         TRACKNUMBER=`metaflac "$a" --show-tag=TRACKNUMBER | sed s/.*=//g`
         DATE=`metaflac "$a" --show-tag=DATE | sed s/.*=//g`

#	 ALACPATH1=`/media/Musikk/ALAC`
#	 echo $ALACPATH1
	 mkdir -p "/media/Musikk/ALAC/$ARTIST/[$DATE] $ALBUM"
#	 mkdir -p "$ALACPATH1/$ARTIST"
#	 ALACPATH2=`"$ALACPATH1/$ARTIST"`
#	 mkdir -p `"$ALACPATH2/[$DATE] $ALBUM"`
	
         flac -c -d "$a" | ffmpeg -i - -acodec alac "$OUTF"
         mp4tags -s "$TITLE" -t "$TRACKNUMBER" -a "$ARTIST" -A "$ALBUM" -g "$GENRE" -y "$DATE" "$ARTIST - $ALBUM - $TRACKNUMBER - $TITLE".m4a
	 echo "OUTF: " $OUTF
	 mv "$OUTF" "/media/Musikk/ALAC/$ARTIST/[$DATE] $ALBUM/"
      done
done
fi
